package dev.minhnh.yetanotherthirst;

import java.util.ArrayList;
import java.util.List;

public final class DefaultItemValues {

    public static List<List<Object>> defaultDrinkValues() {
        List<List<Object>> v = new ArrayList<>();
        add(v, "minecraft:potion", 6, 8);
        add(v, "minecraft:honey_bottle", 3, 4);
        add(v, "minecraft:milk_bucket", 2, 4);
        add(v, Constants.MOD_ID + ":terracotta_water_bowl", 5, 7);
        add(v, Constants.MOD_ID + ":wooden_water_bowl", 5, 7);
        add(v, "farmersrespite:green_tea", 10, 14);
        add(v, "farmersrespite:long_green_tea", 10, 14);
        add(v, "farmersrespite:strong_green_tea", 10, 14);
        add(v, "farmersrespite:yellow_tea", 10, 14);
        add(v, "farmersrespite:long_yellow_tea", 10, 14);
        add(v, "farmersrespite:strong_yellow_tea", 10, 14);
        add(v, "farmersrespite:black_tea", 10, 14);
        add(v, "farmersrespite:long_black_tea", 10, 14);
        add(v, "farmersrespite:strong_black_tea", 10, 14);
        add(v, "farmersrespite:rose_hip_tea", 12, 22);
        add(v, "farmersrespite:long_rose_hip_tea", 12, 22);
        add(v, "farmersrespite:strong_rose_hip_tea", 12, 22);
        add(v, "farmersrespite:dandelion_tea", 12, 22);
        add(v, "farmersrespite:long_dandelion_tea", 12, 22);
        add(v, "farmersrespite:strong_dandelion_tea", 12, 22);
        add(v, "farmersrespite:gamblers_tea", 6, 11);
        add(v, "farmersrespite:long_gamblers_tea", 6, 11);
        add(v, "farmersrespite:strong_gamblers_tea", 6, 11);
        add(v, "farmersrespite:coffee", 6, 11);
        add(v, "farmersrespite:long_coffee", 6, 11);
        add(v, "farmersrespite:strong_coffee", 6, 11);
        add(v, "farmersrespite:strong_melon_juice", 8, 13);
        add(v, "farmersrespite:strong_apple_cider", 8, 13);
        add(v, "create:builders_tea", 12, 22);
        add(v, "farmersdelight:apple_cider", 8, 13);
        add(v, "farmersdelight:melon_juice", 8, 13);
        add(v, "brewinandchewin:beer", 10, 14);
        add(v, "brewinandchewin:vodka", 10, 14);
        add(v, "brewinandchewin:rice_wine", 10, 14);
        add(v, "brewinandchewin:mead", 10, 14);
        add(v, "brewinandchewin:egg_grog", 10, 14);
        add(v, "brewinandchewin:glittering_grenadine", 10, 14);
        add(v, "brewinandchewin:bloody_mary", 12, 22);
        add(v, "brewinandchewin:salty_folly", 12, 22);
        add(v, "brewinandchewin:pale_jane", 12, 22);
        add(v, "brewinandchewin:saccharine_rum", 12, 22);
        add(v, "brewinandchewin:strongroot_ale", 12, 22);
        add(v, "brewinandchewin:dread_nog", 12, 22);
        add(v, "brewinandchewin:kombucha", 14, 22);
        add(v, "brewinandchewin:red_rum", 14, 22);
        add(v, "brewinandchewin:steel_toe_stout", 14, 22);
        add(v, "collectorsreap:pink_limeade", 8, 13);
        add(v, "collectorsreap:berry_limeade", 8, 13);
        add(v, "collectorsreap:limeade", 8, 13);
        add(v, "collectorsreap:pomegranate_black_tea", 10, 14);
        add(v, "collectorsreap:lime_green_tea", 10, 14);
        add(v, "toughasnails:dirty_water_bottle", 6, 8);
        add(v, "toughasnails:purified_water_bottle", 8, 10);
        add(v, "toughasnails:leather_dirty_water_canteen", 8, 10);
        add(v, "toughasnails:leather_water_canteen", 9, 11);
        add(v, "toughasnails:leather_purified_water_canteen", 10, 12);
        add(v, "toughasnails:copper_dirty_water_canteen", 8, 10);
        add(v, "toughasnails:copper_water_canteen", 9, 11);
        add(v, "toughasnails:copper_purified_water_canteen", 10, 12);
        add(v, "toughasnails:iron_dirty_water_canteen", 8, 10);
        add(v, "toughasnails:iron_water_canteen", 9, 11);
        add(v, "toughasnails:iron_purified_water_canteen", 10, 12);
        add(v, "toughasnails:gold_dirty_water_canteen", 8, 10);
        add(v, "toughasnails:gold_water_canteen", 9, 11);
        add(v, "toughasnails:gold_purified_water_canteen", 10, 12);
        add(v, "toughasnails:diamond_dirty_water_canteen", 8, 10);
        add(v, "toughasnails:diamond_water_canteen", 9, 11);
        add(v, "toughasnails:diamond_purified_water_canteen", 10, 12);
        add(v, "toughasnails:netherite_dirty_water_canteen", 8, 10);
        add(v, "toughasnails:netherite_water_canteen", 9, 11);
        add(v, "toughasnails:netherite_purified_water_canteen", 10, 12);
        add(v, "toughasnails:melon_juice", 8, 13);
        add(v, "toughasnails:apple_juice", 8, 13);
        add(v, "toughasnails:cactus_juice", 8, 13);
        add(v, "toughasnails:carrot_juice", 8, 13);
        add(v, "toughasnails:glow_berry_juice", 8, 13);
        add(v, "toughasnails:chorus_fruit_juice", 8, 13);
        add(v, "toughasnails:suspicious_water_cup", 8, 13);
        add(v, "toughasnails:pumpkin_juice", 8, 13);
        add(v, "toughasnails:sweet_berry_juice", 8, 13);
        add(v, "toughasnails:ice_cream", 6, 12);
        add(v, "supernatural:blood_bottle", 6, 8);
        add(v, "farmersdelight:milk_bottle", 2, 4);
        add(v, "brewery:beer_barley", 10, 14);
        add(v, "brewery:beer_haley", 10, 14);
        add(v, "brewery:beer_hops", 10, 14);
        add(v, "brewery:beer_nettle", 10, 14);
        add(v, "brewery:beer_oat", 10, 14);
        add(v, "brewery:beer_wheat", 10, 14);
        add(v, "brewery:dark_brew", 10, 14);
        add(v, "brewery:whiskey_ak", 10, 14);
        add(v, "brewery:whiskey_carrasconlabel", 10, 14);
        add(v, "brewery:whiskey_cristelwalker", 10, 14);
        add(v, "brewery:whiskey_highland_hearth", 10, 14);
        add(v, "brewery:whiskey_jamesons_malt", 10, 14);
        add(v, "brewery:whiskey_jojannik", 10, 14);
        add(v, "brewery:whiskey_lilitusinglemalt", 10, 14);
        add(v, "brewery:whiskey_maggoallan", 10, 14);
        add(v, "brewery:whiskey_smokey_reverie", 10, 14);
        add(v, "farm_and_charm:nettle_tea", 10, 14);
        add(v, "farm_and_charm:nettle_tea_cup", 10, 14);
        add(v, "farm_and_charm:ribwort_tea", 10, 14);
        add(v, "farm_and_charm:ribwort_tea_cup", 10, 14);
        add(v, "farm_and_charm:strawberry_tea", 10, 14);
        add(v, "farm_and_charm:strawberry_tea_cup", 10, 14);
        add(v, "cold_sweat:filled_waterskin", 6, 8);
        return v;
    }

    public static List<List<Object>> defaultFoodValues() {
        List<List<Object>> v = new ArrayList<>();
        add(v, "minecraft:apple", 2, 3);
        add(v, "minecraft:golden_apple", 2, 3);
        add(v, "minecraft:enchanted_golden_apple", 2, 3);
        add(v, "minecraft:melon_slice", 4, 5);
        add(v, "minecraft:carrot", 1, 2);
        add(v, "minecraft:beetroot", 1, 2);
        add(v, "minecraft:sweet_berries", 1, 2);
        add(v, "minecraft:glow_berries", 1, 2);
        add(v, "minecraft:golden_carrot", 1, 2);
        add(v, "minecraft:chorus_fruit", 1, 2);
        add(v, "minecraft:mushroom_stew", 2, 3);
        add(v, "minecraft:rabbit_stew", 2, 3);
        add(v, "minecraft:beetroot_soup", 5, 7);
        add(v, "minecraft:suspicious_stew", 2, 3);
        add(v, "minecraft:cod", 1, 1);
        add(v, "minecraft:salmon", 1, 1);
        add(v, "minecraft:tropical_fish", 1, 2);
        add(v, "minecraft:cooked_cod", 1, 2);
        add(v, "minecraft:cooked_salmon", 1, 2);
        add(v, "minecraft:dried_kelp", 1, 1);
        add(v, "minecraft:bread", 1, 1);
        add(v, "minecraft:pumpkin_pie", 1, 2);
        add(v, "minecraft:cookie", 1, 1);
        add(v, "farmersdelight:pumpkin_slice", 2, 1);
        add(v, "farmersdelight:cabbage_leaf", 1, 2);
        add(v, "farmersdelight:melon_popsicle", 7, 9);
        add(v, "farmersdelight:fruit_salad", 6, 8);
        add(v, "farmersdelight:tomato_sauce", 4, 5);
        add(v, "farmersdelight:mixed_salad", 4, 5);
        add(v, "farmersdelight:beef_stew", 4, 5);
        add(v, "farmersdelight:chicken_soup", 4, 5);
        add(v, "farmersdelight:vegetable_soup", 4, 5);
        add(v, "farmersdelight:fish_stew", 4, 5);
        add(v, "farmersdelight:pumpkin_soup", 4, 5);
        add(v, "farmersdelight:baked_cod_stew", 4, 5);
        add(v, "farmersdelight:noodle_soup", 4, 5);
        add(v, "farmersdelight:bone_broth", 4, 5);
        add(v, "farmersdelight:onion_soup", 4, 5);
        add(v, "farmersdelight:gleaming_salad", 4, 5);
        add(v, "farmersdelight:nether_salad", 2, 3);
        add(v, "farmersdelight:glow_berry_custard", 3, 4);
        add(v, "farmersdelight:apple_pie_slice", 1, 2);
        add(v, "farmersdelight:sweet_berry_cheesecake_slice", 1, 2);
        add(v, "farmersdelight:chocolate_pie_slice", 1, 1);
        add(v, "brewery:potato_salad", 2, 3);
        add(v, "bakery:strawberry_cake_slice", 1, 2);
        add(v, "bakery:sweetberry_cake_slice", 1, 2);
        add(v, "bakery:apple_pie_slice", 1, 2);
        add(v, "bakery:glowberry_pie_slice", 1, 2);
        add(v, "bakery:chocolate_tart_slice", 1, 1);
        add(v, "bakery:linzer_tart_slice", 1, 2);
        add(v, "bakery:pudding_slice", 2, 3);
        add(v, "bakery:bread_with_jam", 1, 2);
        add(v, "bakery:apple_cupcake", 1, 2);
        add(v, "bakery:strawberry_cupcake", 1, 2);
        add(v, "bakery:sweetberry_cupcake", 1, 2);
        add(v, "farm_and_charm:barley_soup", 4, 5);
        add(v, "farm_and_charm:onion_soup", 4, 5);
        add(v, "farm_and_charm:potato_soup", 4, 5);
        add(v, "farm_and_charm:simple_tomato_soup", 4, 5);
        add(v, "farm_and_charm:goulash", 4, 5);
        add(v, "farm_and_charm:oatmeal_with_strawberries", 3, 4);
        add(v, "farm_and_charm:farmer_salad", 4, 5);
        add(v, "farm_and_charm:strawberry", 1, 2);
        add(v, "farm_and_charm:tomato", 2, 3);
        add(v, "collectorsreap:lime_slice", 1, 2);
        add(v, "collectorsreap:lime", 2, 3);
        add(v, "collectorsreap:portobello_rice_soup", 6, 8);
        add(v, "collectorsreap:lime_popsicle", 7, 9);
        return v;
    }

    private static void add(List<List<Object>> list, String id, int thirst, int quenched) {
        list.add(List.of(id, thirst, quenched));
    }

    private DefaultItemValues() {}
}
